### PR TITLE
Create React App Toolchain Instead of Custom Config

### PR DESCRIPTION
**Pull request by IceWreck**
#87

- Compiled/transpiled JS bundle size reduced from one huge 1MB file to several small files totaling to 180KB.
- now gives ESLint warnings etc
- further code splitting and future optimization will be easier if//when needed

### CODE REVIEW

**Comment by IceWreck** [comment]
Can we turn off this auto-commit from pre-commit ?

It wants to change tab width from 4 to 2. Whether  is a good thing or not is up for discussion but this is definitely not the PR for it.

**Review by jpopelka — APPROVED** [review]
Not that I understand JS, but LGTM :-)

**Review by TomasTomecek — APPROVED** [review]
LGTM, very nice!

I'd have some niche points how things could be even better (run-frontend should hint about installing deps if they are not present; the fact it opens a window in my browser was a little unexpected and it took ~20 seconds to print something in console without me knowing what's going on)

Otherwise all things worked great, thank for working on this!

**Review by mfocko — APPROVED** [review]

**Comment by IceWreck** [comment]
Is there a reason this isnt being merged ?

**Comment by mfocko** [comment]
> Is there a reason this isnt being merged ?

@IceWreck Could there be a problem with deployment? If not, I could merge before moving `stable` today

**Comment by IceWreck** [comment]
Well there could be. Can you check the images that GH actions builds before deploying. 

(Stop auto deployment of latest images)

**Comment by mfocko** [comment]
could you rebase or shall I? :)

**Comment by IceWreck** [comment]
Wait let me rebase

**Comment by IceWreck** [comment]
Looks like integrations cant merge modifications to GH actions without a human pressing the button

**Comment by IceWreck** [comment]
buildah is failing, i'll fix it, wait

**Pull request merged**
