### PR TITLE
Usage page backend url fix 2

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
This should work well when deployed but I can't make it work locally..;(

Any suggestion is really welcome!

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]
LGTM (IMHO)

**Comment by lachmanfrantisek** [comment]
> You need to run `make run-dev-frontend` and `make run-dev-flask` in parallel.

That's what I do.

**Comment by mfocko** [comment]
I see the issue now when running it, I guess it might be a firewall issue.

**Comment by lachmanfrantisek** [comment]
recheck

**Pull request merged**
