### PR TITLE
feat(UX): Step timeline for Copr build status

### PR DESCRIPTION
**Pull request by SpyTec**
Introduces a step timeline functionality in place of the existing text fields. Visually it will at a glance give a more holistic view at a glance without removing any of the necessary detail one might want.

Throughout the whole stage, the change will indicate when something started and when it ended. Visually in time-relative means with detailed timedate variant on hover using Tooltips

This should be seen as an MVP as it currently lacks relative information such as build status and links to the different steps. In the future, this can be adapted to other results pages.

visual representation of progress step for Copr builds

TODO:

- [ ] Write new tests or update the old ones to cover new functionality.
- [ ] Update doc-strings where appropriate.
- [ ] Update or write new documentation in `packit/packit.dev`.
- [ ] ‹fill in›

Fixes

Related to

Merge before/after

RELEASE NOTES BEGIN
UX improvement for Copr build timeline
RELEASE NOTES END

### CODE REVIEW

**Review by lbarcziova — APPROVED** [review]
nice UX improvement!

**Comment by SpyTec** [comment]
> I really like this style of representation, thanks!!
> 
> It's also useful for debugging since we have more information presented there.
> 
> Just a small nitpick. I am wondering where to put this timeline. I am slightly disturbed by the alignment with the content on the left...;)
> 
> image
> 
> Maybe put the timeline above the table?

I'll experiment and see what I can come up with, then I'll share it here

**Comment by SpyTec** [comment]
Current
image

Below
image

Above
image

Left
image

Margins removed
image

**Comment by SpyTec** [comment]
> With alignment image

We decided on this change. Merging!

**Pull request merged**
