### PR TITLE
Add label for Usage menu

### PR DESCRIPTION
**Pull request by c3d**
Add label for Usage menu so that it shows up

FIxes: #269

### CODE REVIEW

**Comment by stefwalter** [comment]
Could you provide a screenshot? I can't find the Usage menu item.

**Review by SpyTec — COMMENTED** [review]
LGTM :tada:

**Review by SpyTec — APPROVED** [review]

**Comment by c3d** [comment]
> Could you provide a screenshot? I can't find the Usage menu item.

The link is there, but it does not seem to be doing what we expect.
PR 269

**Comment by SpyTec** [comment]
> > Could you provide a screenshot? I can't find the Usage menu item.
> 
> The link is there, but it does not seem to be doing what we expect. PR 269

It's a bit funky since it fetches from backend. We'd need to use another service. I'll merge it now and when it shows up on the big screen it should work :D

**Pull request merged**
