### PR TITLE
Homepage & status

### PR DESCRIPTION
**Pull request by mfocko**
Signed-off-by: Matej Focko <mfocko@redhat.com>

### CODE REVIEW

**Comment by mfocko** [comment]
https://i.imgur.com/v85ESBy.png

**Comment by jpopelka** [comment]
Looks nice!
I'd probably use just "Packit Service" instead of "Packit-as-a-Service".
I personally (and I'm interested in hearing how the others see it) understand [Packit-as-a-Service as just the Github App](https://github.com/marketplace/packit-as-a-service) (I called it that way, because Packit-Service name was not available If I remember correctly), while the whole machinery I'd call "Packit Service".

**Review by jpopelka — APPROVED** [review]
Thanks!

**Comment by lachmanfrantisek** [comment]
> because Packit-Service name was not available If I remember correctly

That's because it can't collide with existing users/namespaces.

**Review by lachmanfrantisek — APPROVED** [review]
Thanks!

**Comment by TomasTomecek** [comment]
It's now live! Awesome!

I can't wait for time when we swap packit.dev with dashboard.packit.dev/ :D

**Pull request merged**
