### PR TITLE
Results page

### PR DESCRIPTION
**Pull request by IceWreck**
- [x] SRPM Results
- [x] Copr Results page
- [x] Koji results page
- [x] testing farm results
- [x] link result pages to jobs table

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by TomasTomecek** [comment]
indeed needs rebase

**Review by TomasTomecek — APPROVED** [review]
this is pretty awesome! thank you so much for doing this work

**Comment by IceWreck** [comment]
As discussed in #71 
- https://stg.packit.dev/srpm-build/3070/logs  at /results/srpm-builds/3200
- https://stg.packit.dev/copr-build/8830 at /results/copr-builds/8830
- https://prod.packit.dev/koji-build/59 at /results/koji-builds/59
- and /results/testing-farm/12601(no existing plaintext alternative)

**Review by TomasTomecek — APPROVED** [review]
LGTM, stoked to see this in action!

**Comment by csomh** [comment]
Hey @IceWreck, thanks for contributing again! :smile: 

Is this good to be merged from your POV?

**Comment by IceWreck** [comment]
Hey @csomh !

Yes, this is ready.

**Comment by csomh** [comment]
@IceWreck sry, I was late with applying the label. Please rebase this :)

**Comment by lachmanfrantisek** [comment]
@IceWreck thanks a lot!

Since we don't use it for now, here are some examples:
https://dashboard.stg.packit.dev/results/copr-builds/10135 instead of https://stg.packit.dev/copr-build/10135

Screenshot from 2021-03-08 18-58-03

**Pull request merged**
