### PR TITLE
Initial PatternFly v5 upgrade

### PR DESCRIPTION
**Pull request by SpyTec**
This is the ongoing process on getting PatternFly v5 to work

TODO:

- [ ] ‹fill in›

Fixes

Related to

Merge before/after

---

RELEASE NOTES BEGIN
Upgrade PatternFly to v5
RELEASE NOTES END

### CODE REVIEW

**Comment by SpyTec** [comment]
Ready for review. All the deprecated PatternFly components should be addressed separately

**Review by lachmanfrantisek — APPROVED** [review]
Is there any huge change we need to be aware of?

Looking at the page, there is no significant change for the users.

**Comment by SpyTec** [comment]
yolo 😎 

We can go through it on staging for a few days as well

**Comment by SpyTec** [comment]
If something breaks I'll fix it on the weekend

**Pull request merged**
